export default function Home() {
  return (
   <div>
     <div className="flex flex-col items-center justify-center min-h-screen py-2">
       <div className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
         <h1 className="text-6xl font-extrabold text-gray-900">
           Converzone
         </h1>
         <p className="mt-3 text-base text-gray-500">
           Generated by create next app
         </p>
       </div>
     </div>
   </div>
  );
}
